
import './globals.css'
import Navbar from '@/src/components/Navbar'
import BackToTopButton from '@/src/components/BackToTop'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="bg-light-primary">
                <Navbar />
                {children}
                <BackToTopButton />
            </body>
        </html>
    )
}
